// Mocks generated by Mockito 5.4.6 from annotations
// in homework_1/test/presentation/cubits/cat_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cat_swiper/domain/entities/cat.dart' as _i3;
import 'package:cat_swiper/domain/repositories/cat_repository.dart' as _i2;
import 'package:cat_swiper/domain/usecases/fetch_cat_usecase.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCatRepository_0 extends _i1.SmartFake implements _i2.CatRepository {
  _FakeCatRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCat_1 extends _i1.SmartFake implements _i3.Cat {
  _FakeCat_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FetchCatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchCatUseCase extends _i1.Mock implements _i4.FetchCatUseCase {
  MockFetchCatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i5.Future<_i3.Cat> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i5.Future<_i3.Cat>.value(
              _FakeCat_1(this, Invocation.method(#execute, [])),
            ),
          )
          as _i5.Future<_i3.Cat>);
}

/// A class which mocks [LikeCatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikeCatUseCase extends _i1.Mock implements _i4.LikeCatUseCase {
  MockLikeCatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i5.Future<void> execute(_i3.Cat? cat) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [cat]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UnlikeCatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnlikeCatUseCase extends _i1.Mock implements _i4.UnlikeCatUseCase {
  MockUnlikeCatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i5.Future<void> execute(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [GetLikedCatsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLikedCatsUseCase extends _i1.Mock
    implements _i4.GetLikedCatsUseCase {
  MockGetLikedCatsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i5.Future<List<_i3.Cat>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i5.Future<List<_i3.Cat>>.value(<_i3.Cat>[]),
          )
          as _i5.Future<List<_i3.Cat>>);
}

/// A class which mocks [IsCatLikedUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsCatLikedUseCase extends _i1.Mock implements _i4.IsCatLikedUseCase {
  MockIsCatLikedUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i5.Future<bool> execute(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [CheckConnectivityUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckConnectivityUseCase extends _i1.Mock
    implements _i4.CheckConnectivityUseCase {
  MockCheckConnectivityUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCatRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CatRepository);

  @override
  _i5.Future<bool> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
